apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  name: kafka-datagen
  labels:
    eventstreams.ibm.com/cluster: kafka-connect
spec:
  class: com.ibm.eventautomation.demos.loosehangerjeans.DatagenSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    
    #timings.ms.sensorreadings: 27000
    timings.ms.badgeins: 5000

    topic.name.orders: NULLTOPIC
    topic.name.cancellations: NULLTOPIC
    topic.name.stockmovements: NULLTOPIC
    topic.name.badgeins: DOOR.BADGEIN
    #topic.name.newcustomers: NULLTOPIC
    topic.name.sensorreadings: NULLTOPIC
---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-badgeevents
  labels:
    eventstreams.ibm.com/cluster: eventstreams
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 1
  replicas: 1
  topicName: DOOR.BADGEIN

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-nulltopic
  labels:
    eventstreams.ibm.com/cluster: eventstreams
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 1
  replicas: 1
  topicName: NULLTOPIC

---

apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: fake-customers
  labels:
    eventstreams.ibm.com/cluster: eventstreams
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '524288000'
  partitions: 1
  replicas: 1
  topicName: CUSTOMERS.NEW