apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-server-certificate
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
      cert-utils-operator.redhat-cop.io/generate-java-keystores: "true"
  secretName: mq-server-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - mq
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'native-ha-qm-ibm-mq-qm-mq.apps.6602d6121b0194001e821256.cloud.techzone.ibm.com'
    - 'native-ha-qm-ibm-mq-web-mq.apps.6602d6121b0194001e821256.cloud.techzone.ibm.com'
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
