apiVersion: v1
kind: Namespace
metadata:
  name: liberty
  labels:
    clusterresourceoverrides.admission.autoscaling.openshift.io/enabled: "true"
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: mq
  labels:
    clusterresourceoverrides.admission.autoscaling.openshift.io/enabled: "true"
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: eventstreams
  labels:
    clusterresourceoverrides.admission.autoscaling.openshift.io/enabled: "true"
spec: {}