kind: ConfigMap
apiVersion: v1
metadata:
  name: native-ha-qm-configmap
data:
  mq.ini: |
    Channels:
      MaxChannels=200
      MaxActiveChannels=100

  tls.mqsc: |
    DEFINE QLOCAL('QUEUE1') DEFPSIST(YES) REPLACE 
    DEFINE QLOCAL('QUEUE2') DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('QUEUE3') DEFPSIST(YES) REPLACE

    DEFINE QLOCAL('ORDER') DEFPSIST(YES) REPLACE 
    DEFINE QLOCAL('ORDERLOG') REPLACE
    ALTER QLOCAL('ORDER') STRMQOS(BESTEF) STREAMQ('ORDERLOG')

    DEFINE CHANNEL(HAQMCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('TLS_RSA_WITH_3DES_EDE_CBC_SHA') REPLACE
    SET CHLAUTH(HAQMCHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
    
    DEFINE CHANNEL(METRICS) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) REPLACE
    SET CHLAUTH(METRICS) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)

    DEFINE CHANNEL(KAFKA) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) REPLACE
    SET CHLAUTH(KAFKA) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)

