apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 

  - tls/ca-ss-issuer.yaml
  - tls/nativeha-certificate.yaml
  - tls/mq-server-certificate.yaml

  - qm.yaml
  - configmap.yaml

