apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: native-ha-qm-configmap
    files:
      - qm-config/tls.mqsc
      - qm-config/mq.ini

generatorOptions:
  disableNameSuffixHash: true

resources: 

  - tls/ca-ss-issuer.yaml
  - tls/nativeha-certificate.yaml
  - tls/mq-server-certificate.yaml

  - qm.yaml
  #- configmap.yaml

