apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: admin
  labels:
    eventstreams.ibm.com/cluster: eventstreams
    backup.eventstreams.ibm.com/component: kafkauser
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: cluster
        operations: 
          - Alter
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations: 
          - Create
          - Delete
          - Read
          - Write
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - Read