apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - eventstreams-persistent.yaml
  - kafka-admin.yaml
  #- kafka-connect.yaml
  #- kafka-connect-user.yaml
  #- mq-source-connector.yaml
  #- sample-orders-topic.yaml
  #- sample-sink-topic.yaml
  #- topics.yaml
  #- datagen.yaml
