kind: WebSphereLibertyApplication
apiVersion: liberty.websphere.ibm.com/v1
metadata:
  name: websphereliberty-app-sample
  namespace: liberty-sampleapp
spec:
  service:
  type: NodePort
  ports:
    - name: https
      port: 9443
      targetPort: 9443
    - name: iiop
      port: 2809
      targetPort: 2809
      nodePort: 30809
    - name: iiops
      port: 9402
      targetPort: 9402
      nodePort: 30402
  serviceability:
    size: 5Gi
    storageClassName: ocs-storagecluster-cephfs
  securityContext:
    supplementalGroups:
      - 510
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: TBASIC 
  applicationImage: >-
    image-registry.openshift-image-registry.svc:5000/liberty-sampleapp/liberty-sampleapp:latest
  expose: true
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  manageTLS: true
  replicas: 1
  serviceAccount:
    mountToken: true
  volumeMounts:
    - name: config-dropins
      mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/jvm.options
      subPath: jvm.options
  volumes:
    - name: config-dropins
      configMap:
        name: config-dropins
