kind: WebSphereLibertyApplication
apiVersion: liberty.websphere.ibm.com/v1
metadata:
  name: websphereliberty-app-sample
  namespace: liberty-sampleapp
spec:
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: TBASIC 
  applicationImage: >-
    image-registry.openshift-image-registry.svc:5000/liberty-sampleapp/liberty-sampleapp:latest
  expose: true
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  manageTLS: true
  replicas: 1
  serviceAccount:
    mountToken: true
  volumeMounts:
    - name: config-dropins
      mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/jvm.options
      subPath: jvm.options
  volumes:
    - name: config-dropins
      configMap:
        name: config-dropins
