kind: WebSphereLibertyApplication
apiVersion: liberty.websphere.ibm.com/v1
metadata:
  name: websphereliberty-app-sample
spec:
  networkPolicy:
    disable: true
  service:
    type: ClusterIP
    port: 9443
    portName: https
    targetPort: 9443
    ports:
      - port: 2809
        name: iiop
      - port: 9402
        name: iiops
  #serviceability:
  #  size: 5Gi
  #  storageClassName: ocs-storagecluster-cephfs
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: TBASIC 
  applicationImage: >-
    ghcr.io/nordic-mvp-gitops-repos/liberty-sampleapp:latest
  expose: true
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  manageTLS: true
  replicas: 1
  pullPolicy: Always
  serviceAccount:
    mountToken: true
#  volumeMounts:
#    - name: config-dropins
#      mountPath: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides/jvm.options
#      subPath: jvm.options
#  volumes:
#    - name: config-dropins
#      configMap:
#        name: config-dropins
