apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: openliberty-app
spec:
  serviceAccount:
    mountToken: true
  applicationImage: >-
    image-registry.openshift-image-registry.svc:5000/liberty-sampleapp/liberty-sampleapp:latest
  expose: true
  manageTLS: true
  replicas: 1