kind: Service
apiVersion: v1
metadata:
  name: iiop-loadbalancer
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
    service.kubernetes.io/ibm-load-balancer-cloud-provider-vlan: '3393448'
spec:
  type: LoadBalancer 
  selector:
    app.kubernetes.io/instance: websphereliberty-app-sample
  ports:
    - protocol: TCP
      port: 9402
      targetPort: 9402
