apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci
  namespace: openshift-gitops
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: liberty
    server: https://kubernetes.default.svc
  project: liberty
  source:
    path: ./components/ci/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
