apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - argo-role.yaml
  - argo-rolebinding.yaml
  - argo-project.yaml
  - common.yaml
  
  - operators/all-operators.yaml
  - operands/all-operands.yaml

patches:
  - target:
      group: argoproj.io
      kind: ApplicationSet
      labelSelector: group=applications
    patch: |-
      - op: add
        path: /spec/template/spec/source/repoURL
        value: https://github.com/Nordic-MVP-GitOps-Repos/liberty-sampleapp-gitops.git
      - op: add
        path: /spec/template/spec/source/targetRevision
        value: HEAD
  - target:
      group: argoproj.io
      kind: Application
      labelSelector: group=applications
    patch: |-
      - op: add
        path: /spec/source/repoURL
        value: https://github.com/Nordic-MVP-GitOps-Repos/liberty-sampleapp-gitops.git
      - op: add
        path: /spec/source/targetRevision
        value: HEAD