apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - argo-role.yaml
  - argo-rolebinding.yaml
  - common.yaml
  - openshift-monitoring.yaml
  - openshift-logging.yaml
  - liberty-operator.yaml
  - liberty-app.yaml


patches:
  - target:
      group: argoproj.io
      kind: Application
      labelSelector: group=applications
    patch: |-
      - op: add
        path: /spec/source/repoURL
        value: https://github.com/Nordic-MVP-GitOps-Repos/liberty-sampleapp-gitops.git
      - op: add
        path: /spec/source/targetRevision
        value: HEAD