apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-monitoring
  namespace: openshift-gitops
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/openshift-monitoring/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true