apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/main/deploy/releases/1.3.0/kustomize/overlays/watch-all-namespaces/kustomization.yaml