apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 

  - metrics
 
  # Resources for QM using a self signed cerver certificate.
  - native-ha-qm

  - ../../eventstreams/base/letsencrypt-chain.yaml

  # Resources for QM using certificate from LetsEncrypt
  #- native-ha-qm-wellknowncerts