apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - https://github.com/stakater/Reloader/deployments/kubernetes

namespace: mq

patches:
- target:
    version: v1
    kind: Deployment
    name: reloader-reloader
  path: remove-user.yaml
- target:
    version: v1
    kind: Deployment
    name: reloader-reloader
  path: add-reload-strategy.yaml
