apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 
  # Resources for QM using certificate from LetsEncrypt

  - qm.yaml
  - configmap.yaml
  - sni-route.yaml

  - tls/mq-server-certificate.yaml
  - tls/letsencrypt-chain.yaml
  