apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pipeline.yaml
  - pipelinerun.yaml
  - workspace-pvc.yaml
  
  - triggertemplate.yaml
  - eventlistener.yaml
  - route.yaml

  - https://api.hub.tekton.dev/v1/resource/tekton/task/gradle/0.4/raw