apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: plr
spec:
  pipelineRef:
    name: build-image-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: build-workspace